
const KEY="SpeakUp120StateV3";
const phaseData=[
["Foundation: Precision",1,20,"Advanced clarity, sentence control, vocabulary and concise professional delivery."],
["Workplace Influence",21,40,"Meetings, updates, feedback, recommendations, disagreement and professional presence."],
["Law-Firm Fluency",41,60,"Clients, lawyers, adjusters, counsel, medical providers, deadlines and file communication."],
["Difficult Conversations",61,80,"Pressure, conflict, mistakes, boundaries, complaints and difficult calls."],
["Networking & Career Growth",81,100,"Networking, introductions, interviews, relationship building, negotiation and leadership."],
["Mastery",101,120,"Natural, persuasive, precise and confident communication under realistic pressure."]
];
const vocab=[
["circumspect","careful to consider consequences before speaking or acting","I was circumspect in my response because the issue required further review.","measured • prudent • cautious","Speaking: “I’d like to be circumspect before giving a firm answer.” | Writing: “I would prefer to confirm the position before responding.”"],
["substantiate","to support a statement with evidence or facts","The medical documentation may help substantiate the treatment recommendation.","support • corroborate • verify","Speaking: “What documentation can substantiate that position?” | Writing: “Please provide any documentation that substantiates the request.”"],
["nuanced","showing subtle differences or several important aspects","The client's position is more nuanced than the initial summary suggests.","subtle • layered • sophisticated","Speaking: “There’s a more nuanced issue here.” | Writing: “The evidence presents a more nuanced picture.”"],
["expedite","to cause something to happen sooner","Could we expedite the request given the approaching deadline?","accelerate • fast-track • advance","Speaking: “Is there a way to expedite this?” | Writing: “We would appreciate any steps that may expedite the process.”"],
["reconcile","to make two sets of information consistent","I am reconciling the payment history with the ledger before reporting the balance.","align • resolve • harmonize","Speaking: “I’m reconciling the two figures before I confirm the amount.” | Writing: “We are reviewing the records to reconcile the discrepancy.”"],
["mitigate","to reduce the seriousness or impact of something","We should take steps to mitigate the risk of missing the limitation date.","reduce • lessen • alleviate","Speaking: “This would help mitigate the risk.” | Writing: “The proposed step may mitigate the potential delay.”"],
["discretion","careful judgment about what to say or do","The situation required discretion when communicating with the client.","judgment • prudence • tact","Speaking: “I’ll use my discretion and keep the discussion focused.” | Writing: “The matter should be handled with appropriate discretion.”"],
["assertive","confident and direct without being aggressive","A more assertive follow-up may be appropriate at this stage.","direct • self-assured • firm","Speaking: “I want to be assertive without making the message confrontational.” | Writing: “We would appreciate a response by the requested date.”"],
["ambiguous","open to more than one interpretation","The instruction is ambiguous, so I want to confirm the intended next step.","unclear • equivocal • open-ended","Speaking: “I’m not sure how you intended that instruction.” | Writing: “Could you please clarify the intended scope?”"],
["feasible","practical and realistically possible","I can complete the revised draft today if that timeline is feasible.","viable • workable • practical","Speaking: “That timeline is feasible from my end.” | Writing: “Please let me know whether the proposed timeline is feasible.”"],
["constructive","useful and intended to improve something","I appreciate the constructive feedback and will apply it to the next draft.","productive • helpful • solution-focused","Speaking: “That’s helpful feedback; I’ll incorporate it.” | Writing: “Thank you for the constructive comments.”"],
["proactive","acting before a problem requires action","I wanted to be proactive and flag the upcoming deadline.","anticipatory • forward-looking • initiative-taking","Speaking: “I wanted to flag this proactively.” | Writing: “I am writing proactively to avoid a last-minute issue.”"],
["allocate","to assign time, resources or responsibility","I can allocate time this afternoon to complete the production review.","assign • devote • distribute","Speaking: “I can allocate an hour this afternoon.” | Writing: “I have allocated time to complete the review.”"],
["tactful","careful not to offend or embarrass","I would take a tactful approach when raising the concern.","diplomatic • considerate • measured","Speaking: “I’d raise it tactfully and focus on the issue.” | Writing: “I would suggest a tactful response that acknowledges the concern.”"],
["articulate","able to express an idea clearly and effectively","She articulated the concern clearly during the meeting.","express • convey • formulate","Speaking: “Let me articulate the concern clearly.” | Writing: “The letter should articulate the client's position concisely.”"],
["pertinent","directly relevant to the matter being discussed","Please send any documents that are pertinent to the issue.","relevant • material • applicable","Speaking: “That point is pertinent to the discussion.” | Writing: “Please address the pertinent issues in your response.”"],
["discrepancy","a difference between two things that should match","I noticed a discrepancy between the ledger and the payment history.","inconsistency • variance • mismatch","Speaking: “There’s a discrepancy I’d like to verify.” | Writing: “We note a discrepancy between the two records.”"],
["convey","to communicate an idea, feeling or information","The email should convey the urgency without sounding confrontational.","communicate • express • impart","Speaking: “I want to convey the urgency clearly.” | Writing: “The correspondence should convey the requested position.”"],
["comprehensive","complete and covering all important aspects","I prepared a comprehensive summary of the outstanding issues.","thorough • exhaustive • complete","Speaking: “I’ll prepare a comprehensive update.” | Writing: “Attached is a comprehensive summary for review.”"],
["pragmatic","focused on practical results rather than theory","A pragmatic approach would be to resolve the outstanding document issue first.","practical • realistic • results-oriented","Speaking: “I’d take a pragmatic approach here.” | Writing: “A pragmatic solution may be preferable at this stage.”"]
];
const situations=[
["File-status update","A lawyer asks, “Where are we with this file?”","Give a 45-second update: current status → outstanding item → action you are taking → when you will update again."],
["Clarifying an instruction","You receive an instruction that could be interpreted in two ways.","Ask a precise clarification without sounding hesitant or repeatedly apologetic."],
["Client frustration","A client says, “I keep calling and nobody tells me anything.”","Acknowledge the frustration, state what you can confirm, and set a concrete next step."],
["Adjuster follow-up","An insurer has not responded and a deadline is approaching.","Be firm, courteous and specific about the requested response."],
["Medical-provider issue","A clinic says it did not receive a requested document or payment.","Clarify what happened, ask what they need, and establish the follow-up."],
["Admitting a mistake","You sent the wrong attachment.","Own it briefly, correct it, and tell the recipient exactly what to rely on now."],
["Professional disagreement","You believe a proposed approach creates avoidable risk.","Explain the concern and offer an alternative without challenging the person."],
["Competing deadlines","A supervisor gives you another urgent task while two deadlines are active.","Ask for priority guidance using facts rather than saying you are simply too busy."],
["Meeting contribution","You have a useful point after several people have spoken.","Enter naturally, add value, and avoid repeating what others already said."],
["Difficult caller","Someone becomes impatient and interrupts repeatedly.","Regain structure politely and guide the conversation toward a solution."],
["Settlement discussion","You need to explain why a number or issue needs clarification before closing.","State the discrepancy, what supports your position, and what you propose next."],
["LAT/file preparation","You need a missing item before a filing can be finalized.","Explain the missing piece and deadline without making the request sound accusatory."],
["New lawyer introduction","A new lawyer joins the firm and you will support their files.","Introduce your role, explain what you handle, and invite their preferences for workflow."],
["Feedback conversation","A senior colleague gives you feedback you partly disagree with.","Acknowledge the useful part, ask a focused question, and discuss the point professionally."],
["Priority escalation","A limitation date is approaching and an item remains outstanding.","Escalate early with the essential facts and a recommended action."]
];
const writingTasks=[
["Follow-up email","You are following up because you have not received the requested documents.","Write a concise email with context, outstanding item, requested action and a reasonable closing."],
["Internal status update","Your lawyer needs a quick update on what is done and what remains.","Write 4–6 sentences using short, decisive sentences."],
["Client email","The client wants an immediate answer, but you need to confirm the file first.","Acknowledge the message without guessing. Explain what you will confirm and when."],
["Professional correction","You realize a previous email contained an error.","Write a short correction that takes responsibility without over-explaining."],
["Meeting recap","Turn a messy discussion into a clear written recap.","Write the decisions, outstanding items, owners and next steps."]
];
const networking=[
["30-second introduction","Introduce yourself to a lawyer or legal professional at an event.","Name → role → area you work in → genuine reason for being interested in their work."],
["Follow-up after meeting","You met someone useful and want to stay connected.","Write a short follow-up that refers to the conversation rather than using a generic networking message."],
["Informational question","You want to learn how someone moved into their current practice area.","Ask an open question that encourages a useful story, not a yes/no answer."],
["Professional small talk","You are waiting before a seminar begins.","Start naturally, then move from the event into professional conversation."],
["Career conversation","Someone asks what direction you want to take your career.","Explain your strengths and interests without sounding dissatisfied with your current role."]
];
const novel=[
["Pride and Prejudice","Jane Austen","It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.","Notice how the sentence sounds authoritative while quietly setting up irony."],
["Jane Eyre","Charlotte Brontë","I am no bird; and no net ensnares me: I am a free human being with an independent will.","Read for conviction. Notice how punctuation creates emphasis and rhythm."],
["Great Expectations","Charles Dickens","My father's family name being Pirrip, and my Christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip.","Notice narrative voice, long sentence structure and how a detail is made memorable."],
["David Copperfield","Charles Dickens","Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show.","Notice the rhetorical question and how the sentence creates anticipation."]
];
const blogs=[
["The structure that makes you sound confident","Confidence is often structural. State the point first, add only the context needed, then give the next step. This prevents long explanations from becoming uncertain.","Try: Point → context → action. Then remove one sentence you do not need."],
["A professional follow-up is not an apology","A follow-up should make the status visible and make the next action easy. You can be persistent without sounding irritated.","Use: “I’m following up regarding ___. We are still awaiting ___. Could you please confirm ___?”"],
["How to disagree without sounding difficult","Separate the issue from the person. Name the concern, explain the consequence, and offer an alternative.","Try: “One concern I see is ___. Would it make sense to consider ___?”"],
["Why strong speakers pause","A pause can make a sentence sound deliberate. Filling every silence with “um,” “just,” or “maybe” often weakens the message.","Before answering a difficult question, take one calm breath, then begin with your point."],
["Networking is curiosity, not performance","The best networking conversations are not sales pitches. They are exchanges where you listen for something specific and ask a better second question.","Ask: “What led you into that area?” then build your next question from the answer."]
];
const days=[];
const topics=["precision in updates","professional questions","concise explanations","follow-ups","meeting contributions","priority setting","feedback","recommendations","disagreement","client empathy","deadline communication","explaining process","risk language","professional small talk","summarizing decisions","asking for direction","owning mistakes","difficult callers","escalating early","natural workplace English"];
for(let d=1;d<=120;d++){
 let p=phaseData.find(x=>d>=x[1]&&d<=x[2]); let pi=phaseData.indexOf(p);
 let level=d<=20?"Advanced precision":d<=40?"Professional influence":d<=60?"Law-firm fluency":d<=80?"Difficult situations":d<=100?"Networking & growth":"Mastery";
 days.push({day:d,phase:p[0],level,topic:topics[(d-1)%topics.length],vocab:vocab[(d-1)%vocab.length],situation:situations[(d-1)%situations.length],writing:writingTasks[(d-1)%writingTasks.length],networking:networking[(d-1)%networking.length],novel:novel[(d-1)%novel.length],phaseIndex:pi});
}
let state=(()=>{const blank={startDate:new Date().toISOString().slice(0,10),completed:{},history:{},answers:{},scores:{},notes:"",recordings:[],selectedDay:1,streak:0,lastCompleted:null,typingBest:0};try{const raw=localStorage.getItem(KEY);if(!raw)return blank;const saved=JSON.parse(raw);return {...blank,...saved,completed:{...blank.completed,...(saved.completed||{})},history:{...blank.history,...(saved.history||{})},answers:{...blank.answers,...(saved.answers||{})},scores:{...blank.scores,...(saved.scores||{})},recordings:Array.isArray(saved.recordings)?saved.recordings:[]};}catch(e){console.warn("SpeakUp storage reset:",e);return blank;}})();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dayNow(){let s=new Date((state.startDate||new Date().toISOString().slice(0,10))+"T00:00:00"),n=new Date();let x=Math.floor((new Date(n.getFullYear(),n.getMonth(),n.getDate())-new Date(s.getFullYear(),s.getMonth(),s.getDate()))/86400000)+1;return Math.min(120,Math.max(1,x))}
function current(){let d=Math.min(120,Math.max(1,Number(state.selectedDay)||dayNow())); state.selectedDay=d; return days[d-1]}
function doneCount(){return Object.keys(state.completed).length}
function dayDone(d){return Object.keys(state.completed).filter(k=>k.startsWith(d+"|")).length}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function go(v){if(!v)return; const allowed=['today','journey','history','speaking','vocabulary','workplace','reading','writing','typing','networking','confidence','library','notes','settings']; if(!allowed.includes(v))v='today'; if(location.hash.slice(1)!==v) location.hash=v; else render();}
function mark(key,score=0,day=current().day){
 state.completed[day+"|"+key]=true;state.scores[day+"|"+key]=Math.max(score,state.scores[day+"|"+key]||0);
 state.history[day] ||= {date:new Date().toLocaleDateString(),items:[],scores:{}};
 if(!state.history[day].items.includes(key))state.history[day].items.push(key);
 state.history[day].scores[key]=Math.max(score,state.history[day].scores[key]||0);
 if(state.lastCompleted===day-1||state.lastCompleted===day)state.streak=Math.max(1,state.streak+1);else state.streak=1;
 state.lastCompleted=day;save();toast("Saved to Day "+day);render();
}
function evaluate(text){
 let words=(text.match(/\b[\w’'-]+\b/g)||[]).length;
 let fillers=(text.match(/\b(um|uh|like|just|maybe|basically|actually|sort of|kind of|you know)\b/gi)||[]).length;
 let clarity=Math.max(30,Math.min(100,48+Math.min(words,40)*1.15-fillers*4));
 let structure=45+(words>=15?16:0)+(words>=30?10:0)+(/[.!?]/.test(text)?12:0)+(/\b(next|confirm|update|recommend|will|can|could|would)\b/i.test(text)?12:0);
 let tone=55+(/\b(please|appreciate|understand|confirm|recommend|would|could|thank)\b/i.test(text)?17:0)+(fillers===0?12:0);
 let scores=[Math.min(100,clarity),Math.min(100,structure),Math.min(100,tone)];
 return {words,fillers,clarity:Math.round(scores[0]),structure:Math.round(scores[1]),tone:Math.round(scores[2]),overall:Math.round(scores.reduce((a,b)=>a+b)/3)}
}
function feedback(text){
 if(!text.trim())return '<div class="feedback"><h4>Feedback</h4><p class="mini">Write or speak an answer first.</p></div>';
 let s=evaluate(text), tips=[];
 if(s.words<15)tips.push("Add one specific detail and finish with a clear next step.");
 if(s.words>70)tips.push("Tighten the response. Use shorter thought units.");
 if(s.fillers)tips.push("You used "+s.fillers+" filler-word occurrence(s). Replace them with a pause.");
 if(s.structure<75)tips.push("Use Point → Context → Action so the listener knows where you are going.");
 if(s.tone<75)tips.push("Choose direct, courteous verbs such as confirm, recommend, clarify or update.");
 if(!tips.length)tips.push("Strong structure. Try one more attempt with 10–15% fewer words.");
 return `<div class="feedback"><h4>Feedback on this attempt</h4><div class="fbgrid">${[['Overall',s.overall],['Clarity',s.clarity],['Structure',s.structure],['Tone',s.tone]].map(x=>`<div class="pill"><b>${x[1]}</b><small>${x[0]}</small></div>`).join("")}</div><ul>${tips.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p class="mini"><b>Words:</b> ${s.words} · <b>Fillers:</b> ${s.fillers}</p></div>`;
}
function examplesFor(sit){
 return [
 ["Simple","I’ll check and let you know.","Use when the matter is straightforward."],
 ["Clear","I’ll review the file and let you know what I find.","Use when you want the action to be explicit."],
 ["Natural","I’ll review the file and get back to you once I’ve confirmed the details.","Use for everyday office communication."],
 ["Confident","I’ll review the file, confirm the outstanding points, and update you this afternoon.","Use when you can commit to a next step."],
 ["Strong professional","I’ll review the file and confirm the outstanding points. I’ll send you a concise update this afternoon, including anything that requires your direction.","Use when the communication has real professional stakes."]
 ];
}
function renderToday(){
 let d=current(), completed=dayDone(d.day), total=6;
 return `<div class="hero"><div><span class="eyebrow">${esc(d.phase)} · ${esc(d.level)}</span><h1>Day ${d.day}: ${esc(d.topic)}</h1><p>One integrated practice day. Speak, learn advanced vocabulary, handle a realistic workplace situation, read, write and type. Every result is saved to your Daily Progress journal.</p><div class="actions" style="margin-top:17px"><button class="btn" onclick="go('speaking')">Start speaking</button><button class="btn secondary" onclick="go('history')">Review every day</button></div></div><div class="hero-day"><b>${completed}<small>/ ${total}</small></b><small>today's core activities</small></div></div>
<div class="section grid g4">${[['120-day progress',Math.round(doneCount()/720*100)+'%','6 core activities × 120 days'],['Current day','Day '+d.day,'of 120'],['Streak',state.streak+' days','practice streak'],['Side notes',state.notes.trim()?'Saved':'Empty','always available']].map(x=>`<div class="card stat"><b>${x[1]}</b><small>${x[0]} · ${x[2]}</small></div>`).join("")}</div>
<div class="section two"><div><div class="head"><div><h2>Today's integrated practice</h2><p>Finish the six core blocks; revisit anything you want.</p></div></div><div class="practice">${[['Speaking','Record + written transcript + feedback','speaking','speaking'],['Vocabulary','Meaning + 5 contexts + alternatives','vocabulary','vocabulary'],['Workplace situation',d.situation[0]+' · law-firm realism','workplace','workplace'],['Novel reading','Read, interpret and respond','reading','reading'],['Writing','Draft + proofread + compare','writing','writing'],['Typing','Speed + accuracy + feedback','typing','typing']].map(x=>`<div class="practice-row"><div><b>${x[0]}</b><small>${esc(x[1])}</small></div><button class="btn ghost" onclick="go('${x[2]}')">${state.completed[d.day+'|'+x[3]]?'Review':'Open'}</button></div>`).join("")}</div></div>
<div><div class="head"><div><h2>Today's word</h2></div></div><div class="card"><span class="tag">${esc(d.level)}</span><div class="word">${esc(d.vocab[0])}</div><p class="definition">${esc(d.vocab[1])}</p><p class="mini"><b>Work example:</b> ${esc(d.vocab[2])}</p><p class="alt"><b>Alternatives:</b> ${esc(d.vocab[3])}</p><button class="btn" onclick="go('vocabulary')">Practise it in context</button></div>
<div class="card section"><h3>Today's confidence cue</h3><p class="mini">Pause before your answer. Lead with the point. A calm pause sounds more confident than filling silence.</p><button class="btn secondary" onclick="go('confidence')">Open confidence lab</button></div></div></div>`;
}
function renderJourney(){
 return `<div class="head"><div><h2>120-Day Journey</h2><p>Choose any day to review it. Your current day is highlighted.</p></div><button class="btn" onclick="selectDay(dayNow())">Go to today</button></div>
<div class="card"><div class="head"><div><h3 style="margin:0">Curriculum map</h3><p>${doneCount()} activities completed</p></div><span class="tag">${Math.round(doneCount()/720*100)}%</span></div><div class="day-grid">${days.map(d=>`<button class="day-cell ${d.day===dayNow()?'current':''} ${d.day===state.selectedDay?'selected':''} ${dayDone(d.day)?'done':''}" onclick="selectDay(${d.day})"><b>${d.day}</b>${esc(d.topic)}</button>`).join("")}</div></div>
<div class="section grid g3">${phaseData.map(p=>`<div class="phase-card"><span class="tag">Days ${p[1]}–${p[2]}</span><h3>${p[0]}</h3><p>${p[3]}</p><div class="progress"><i style="width:${Math.round((Array.from({length:p[2]-p[1]+1},(_,i)=>dayDone(p[1]+i)).reduce((a,b)=>a+(b>0?1:0),0)/(p[2]-p[1]+1))*100)}%"></i></div></div>`).join("")}</div>
<div class="section card"><h3>Selected day: Day ${state.selectedDay}</h3><p class="mini">${esc(days[state.selectedDay-1].phase)} · ${esc(days[state.selectedDay-1].topic)}</p><div class="actions"><button class="btn" onclick="go('speaking')">Open selected-day speaking</button><button class="btn secondary" onclick="go('history')">Review journal</button></div></div>`;
}
function selectDay(n){state.selectedDay=n;save();render()}
function renderHistory(){
 let rows=Object.keys(state.history).map(Number).sort((a,b)=>b-a);
 return `<div class="head"><div><h2>Daily Progress Journal</h2><p>This is the place to look back on every day — date, activities, scores, answers and notes.</p></div><div class="actions"><button class="btn secondary" onclick="exportData()">Export my data</button><button class="btn" onclick="go('journey')">Open all 120 days</button></div></div>
<div class="card"><table class="history-table"><thead><tr><th>Day</th><th>Date</th><th>Topic</th><th>Everything practiced</th><th>Average</th><th>Review</th></tr></thead><tbody>${rows.length?rows.map(d=>{let h=state.history[d],vals=Object.values(h.scores||{});return `<tr><td><b>Day ${d}</b></td><td>${esc(h.date)}</td><td>${esc(days[d-1]?.topic||'')}</td><td>${h.items.map(i=>`<span class="chip">${esc(i)}</span>`).join('')}</td><td>${vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):'—'}</td><td><button class="btn ghost" onclick="selectDay(${d})">Review day</button></td></tr>`}).join(''):`<tr><td colspan="6"><div class="empty">Your first completed activity will appear here. Nothing is lost: each activity records its day and date.</div></td></tr>`}</tbody></table></div>
${state.selectedDay?renderDayReview(state.selectedDay):''}`;
}
function renderDayReview(d){
 let h=state.history[d],a=state.answers[d]||{};
 return `<div class="section card"><div class="head"><div><h3>Day ${d} review</h3><p>${h?esc(h.date):'Not completed yet'} · ${esc(days[d-1].phase)}</p></div><span class="tag">${dayDone(d)}/6 core activities</span></div>
<div class="grid g3">${[['Speaking',a.speaking||'No saved written transcript'],['Vocabulary',a.vocabulary||'No written response saved'],['Workplace',a.workplace||'No response saved'],['Reading',a.reading||'No reading reflection saved'],['Writing',a.writing||'No draft saved'],['Typing',a.typing||'No typing attempt saved']].map(x=>`<div class="card" style="padding:12px"><b>${x[0]}</b><p class="mini">${esc(x[1])}</p></div>`).join("")}</div>
${h?`<div class="section"><b>Scores</b><div class="grid g4">${Object.entries(h.scores||{}).map(x=>`<div class="pill"><b>${x[1]}</b><small>${esc(x[0])}</small></div>`).join("")}</div></div>`:''}</div>`;
}
function renderSpeaking(){
 let d=current(),s=d.situation, ans=state.answers[d.day]?.speaking||'';
 return `<div class="head"><div><h2>Speaking Lab · Day ${d.day}</h2><p>Real recording + transcript + structured feedback. Nothing here is a fake recorder.</p></div><span class="tag">${esc(s[0])}</span></div>
<div class="two"><div><div class="card"><h3>${esc(s[1])}</h3><p class="mini">${esc(s[2])}</p><div class="callout"><b>Speaking structure:</b> Point → Context → Action. Aim for 30–60 seconds. Pause instead of filling silence.</div><textarea id="speakAnswer" class="answer" placeholder="Type your answer here, or record first and then add a transcript...">${esc(ans)}</textarea><div class="actions" style="margin-top:9px"><button class="btn" id="fbSpeak">Feedback on my answer</button><button class="btn green" id="saveSpeak">Save to Day ${d.day}</button></div><div id="speakFeedback"></div></div>
<div class="card section"><h3>Five versions — learn the movement, not a script</h3><div class="examples">${examplesFor(s).map(x=>`<div class="example"><div class="level">${x[0]}</div><p>${esc(x[1])}</p><small>${esc(x[2])}</small></div>`).join('')}</div></div></div>
<div><div class="card record" id="recBox"><div><span class="dot"></span><span id="recState">Ready</span></div><div class="timer" id="recTimer">00:00</div><button class="btn" id="recBtn">Start recording</button><p class="mini">Saved locally in your browser. You can replay or delete it later.</p></div><div class="card section"><h3>My saved recordings</h3><div id="audioList"><div class="empty">No recordings yet.</div></div></div></div></div>`;
}
let recorder=null,chunks=[],startAt=0,intv=null;
async function beginRecord(){try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);startAt=Date.now();recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());let blob=new Blob(chunks,{type:'audio/webm'}),id=Date.now();await putAudio(id,blob);state.recordings.unshift({id,day:current().day,date:new Date().toLocaleString(),title:current().topic});save();render();toast('Recording saved');};recorder.start();document.getElementById('recBox').classList.add('recording');document.getElementById('recBtn').textContent='Stop & save';document.getElementById('recState').textContent='Recording…';intv=setInterval(()=>document.getElementById('recTimer').textContent=fmt(Date.now()-startAt),250);document.getElementById('recBtn').onclick=endRecord}catch(e){toast('Microphone access was not available')}}
function endRecord(){if(recorder?.state==='recording'){recorder.stop();clearInterval(intv)}}
function fmt(ms){let s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
let dbp;function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{let r=indexedDB.open('SpeakUpAudio120V3',1);r.onupgradeneeded=()=>r.result.createObjectStore('audio');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function putAudio(id,b){let d=await db();return new Promise((res,rej)=>{let t=d.transaction('audio','readwrite');t.objectStore('audio').put(b,id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function getAudio(id){let d=await db();return new Promise((res,rej)=>{let r=d.transaction('audio').objectStore('audio').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function loadAudio(){let el=document.getElementById('audioList');if(!el)return;if(!state.recordings.length){el.innerHTML='<div class="empty">No recordings yet.</div>';return}el.innerHTML='';for(let r of state.recordings.slice(0,20)){let b=await getAudio(r.id),url=b?URL.createObjectURL(b):'';let row=document.createElement('div');row.className='audio-row';row.innerHTML=`<div><b>Day ${r.day}</b><small class="muted" style="display:block">${esc(r.date)}</small></div>${url?`<audio controls src="${url}"></audio>`:'<small>Audio unavailable</small>'}<button class="btn ghost" onclick="deleteAudio(${r.id})">×</button>`;el.appendChild(row)}}
async function deleteAudio(id){let d=await db();d.transaction('audio','readwrite').objectStore('audio').delete(id);state.recordings=state.recordings.filter(x=>x.id!==id);save();loadAudio()}
function renderVocabulary(){let d=current(),w=d.vocab;let response=state.answers[d.day]?.vocabulary||'';return `<div class="head"><div><h2>Advanced Vocabulary Studio · Day ${d.day}</h2><p>Meaning → nuance → alternatives → spoken use → written use → your own sentence.</p></div><button class="btn secondary" onclick="nextWord()">New word</button></div><div class="two"><div><div class="card"><span class="tag">${esc(d.level)}</span><div class="word">${esc(w[0])}</div><p class="definition">${esc(w[1])}</p><div class="callout"><b>Law-firm/work example:</b> ${esc(w[2])}</div><p class="alt"><b>Alternatives:</b> ${esc(w[3])}</p><p class="mini"><b>Other ways to use it:</b> ${esc(w[4])}</p></div><div class="card section"><h3>Your practice</h3><p class="mini">Write one sentence using the word naturally. Then write a different version without using the word.</p><textarea id="vocabAnswer" class="answer">${esc(response)}</textarea><div class="actions" style="margin-top:8px"><button class="btn" id="fbVocab">Get feedback</button><button class="btn green" id="saveVocab">Save vocabulary practice</button></div><div id="vocabFeedback"></div></div></div><div><div class="card"><h3>Context ladder</h3>${[['Spoken at work','Use it naturally in a meeting or call.'],['Professional email','Use it without sounding overly formal.'],['Client-facing','Explain the same idea in plain language.'],['Internal file note','Make it concise and factual.'],['Networking/interview','Use it to describe your judgment or experience.']].map(x=>`<div class="example"><div class="level">${x[0]}</div><p>${x[1]}</p></div>`).join('')}</div></div></div>`}
function nextWord(){state.selectedWord=(state.selectedWord||0)+1;let idx=state.selectedWord%vocab.length;let d=current();d.vocab=vocab[idx];render()}
function renderWorkplace(){let d=current(),s=d.situation,a=state.answers[d.day]?.workplace||'';return `<div class="head"><div><h2>Workplace & Law-Firm Scenarios · Day ${d.day}</h2><p>Realistic practice based on the communication patterns you work with: files, lawyers, clients, adjusters, counsel, medical providers, deadlines and follow-ups.</p></div></div><div class="two"><div><div class="card"><span class="tag">${esc(s[0])}</span><h3>${esc(s[1])}</h3><p class="mini">${esc(s[2])}</p><div class="callout"><b>Do not memorize.</b> First answer naturally. Then compare your structure with the five model versions.</div><textarea id="workAnswer" class="answer" placeholder="What would you say?">${esc(a)}</textarea><div class="actions" style="margin-top:8px"><button class="btn" id="fbWork">Get detailed feedback</button><button class="btn green" id="saveWork">Save scenario</button></div><div id="workFeedback"></div></div><div class="card section"><h3>Five response levels</h3><div class="examples">${examplesFor(s).map(x=>`<div class="example"><div class="level">${x[0]}</div><p>${esc(x[1])}</p><small>${esc(x[2])}</small></div>`).join('')}</div></div></div><div><div class="card"><h3>Professional checklist</h3>${['Lead with the point','Give only relevant context','Use a calm, direct tone','State the action or next step','Close with a clear expectation'].map(x=>`<label class="check"><input type="checkbox"> ${x}</label>`).join('')}</div><div class="card section"><h3>What else could be said?</h3><p class="mini">Try the same message in three registers: concise internal, natural spoken, polished written.</p><div class="example"><div class="level">Concise internal</div><p>“I’m reviewing the outstanding item and will update you once confirmed.”</p></div><div class="example"><div class="level">Natural spoken</div><p>“I’m checking that now. I’ll let you know as soon as I have confirmation.”</p></div><div class="example"><div class="level">Polished written</div><p>“I am reviewing the outstanding item and will provide an update once the details have been confirmed.”</p></div></div></div></div>`}
function renderReading(){let d=current(),n=d.novel,a=state.answers[d.day]?.reading||'';return `<div class="head"><div><h2>Novel Reading Studio · Day ${d.day}</h2><p>Public-domain classics selected for advanced vocabulary, rhythm, inference and expressive reading.</p></div></div><div class="two"><div><div class="card"><span class="tag">${esc(n[1])}</span><h3>${esc(n[0])}</h3><div class="reading">${esc(n[2])}</div><p class="mini"><b>Reading focus:</b> ${esc(n[3])}</p><div class="actions"><button class="btn secondary" id="readAloud">Read aloud with browser voice</button><button class="btn ghost" id="stopRead">Stop</button></div></div><div class="card section"><h3>Interpretation practice</h3><p class="mini">What is the author doing here? What makes the sentence effective? Explain it in your own words.</p><textarea id="readingAnswer" class="answer">${esc(a)}</textarea><div class="actions" style="margin-top:8px"><button class="btn" id="fbRead">Get feedback</button><button class="btn green" id="saveRead">Save reading practice</button></div><div id="readFeedback"></div></div></div><div><div class="card"><h3>Reading skills</h3>${['Read once for meaning','Read again for rhythm','Underline unfamiliar words','Infer before looking up','Retell the idea in plain English','Notice sentence structure'].map(x=>`<label class="check"><input type="checkbox"> ${x}</label>`).join('')}</div><div class="card section"><h3>Why novels?</h3><p class="mini">Fiction exposes you to rhythm, nuance, implied meaning, precise adjectives and long sentence structures that everyday workplace writing often does not. The goal is to transfer those skills into professional English—not to imitate literary language at work.</p></div></div></div>`}
function renderWriting(){let d=current(),t=d.writing,a=state.answers[d.day]?.writing||'';return `<div class="head"><div><h2>Writing & Proofreading · Day ${d.day}</h2><p>Draft, diagnose, rewrite, then compare the register.</p></div></div><div class="two"><div><div class="card"><span class="tag">${esc(t[0])}</span><h3>${esc(t[1])}</h3><p class="mini">${esc(t[2])}</p><div class="callout"><b>Proofread for:</b> unnecessary words · vague verbs · tone · missing context · missing next step · grammar · punctuation.</div><textarea id="writeAnswer" class="answer" placeholder="Write your professional version...">${esc(a)}</textarea><div class="actions" style="margin-top:8px"><button class="btn" id="fbWrite">Get writing feedback</button><button class="btn green" id="saveWrite">Save writing</button></div><div id="writeFeedback"></div></div></div><div><div class="card"><h3>Quick proofreading lens</h3>${[['Clarity','Can someone understand the point on the first read?'],['Precision','Did you use the exact action/issue instead of a vague phrase?'],['Tone','Firm, courteous and professional?'],['Economy','Can a sentence be shorter without losing meaning?'],['Next step','Does the reader know what happens next?']].map(x=>`<div class="example"><div class="level">${x[0]}</div><p>${x[1]}</p></div>`).join('')}</div><div class="card section"><h3>Before → stronger</h3><div class="example"><div class="level">Less effective</div><p>“I just wanted to follow up and see if maybe you had a chance to look at this.”</p></div><div class="example"><div class="level">More professional</div><p>“I’m following up regarding the documents below. Could you please confirm when we can expect them?”</p></div></div></div></div>`}
function renderTyping(){let d=current(),source=`I am reviewing the outstanding items and will provide a concise update once the relevant documents have been confirmed. If anything further is required from my end, I will address it promptly and keep the file moving.`;return `<div class="head"><div><h2>Typing Lab · Day ${d.day}</h2><p>Professional text, accuracy first, then speed. Your best result is stored locally.</p></div></div><div class="two"><div class="card"><div class="typing-source" id="typingSource">${source}</div><textarea id="typingInput" class="answer typing-area" placeholder="Type the passage exactly..."></textarea><div class="actions" style="margin-top:8px"><button class="btn" id="typingCheck">Check accuracy</button><button class="btn secondary" id="typingClear">Clear</button></div><div id="typingFeedback"></div></div><div class="card"><h3>Your typing record</h3><div class="stat"><b id="typingBest">${state.typingBest||0}%</b><small>best accuracy</small></div><p class="mini">Target: 95%+ accuracy before increasing speed.</p></div></div>`}
function renderNetworking(){let d=current(),n=d.networking,a=state.answers[d.day]?.networking||'';return `<div class="head"><div><h2>Networking Studio · Day ${d.day}</h2><p>Professional relationship-building without sounding scripted or salesy.</p></div><span class="tag">${esc(n[0])}</span></div><div class="two"><div class="card"><h3>${esc(n[1])}</h3><p class="mini">${esc(n[2])}</p><div class="callout"><b>Advanced goal:</b> sound interested, specific and natural. Avoid a memorized “elevator pitch.”</div><textarea id="networkAnswer" class="answer" placeholder="Write what you would say...">${esc(a)}</textarea><div class="actions" style="margin-top:8px"><button class="btn" id="fbNetwork">Get feedback</button><button class="btn green" id="saveNetwork">Save networking practice</button></div><div id="networkFeedback"></div></div><div><div class="card"><h3>Conversation ladder</h3>${['Open naturally','Ask a specific question','Listen for a detail','Build the next question from their answer','Close with a genuine reason to stay connected'].map((x,i)=>`<div class="practice-row"><div><b>${i+1}. ${x}</b></div></div>`).join('')}</div><div class="card section"><h3>Useful advanced questions</h3>${['What led you to that area of practice?','What has been the most useful skill in that transition?','What kind of matters do you find most interesting?','What would you recommend someone build early in their career?','What are you seeing change in the field?'].map(x=>`<div class="example"><p>“${x}”</p></div>`).join('')}</div></div></div>`}
function renderConfidence(){return `<div class="head"><div><h2>Confidence & Professional Presence</h2><p>Train the behaviours that make communication sound calm, capable and deliberate.</p></div></div><div class="grid g3">${[['Pause','Take one breath before difficult answers. Silence is not failure.','Before answering a senior person, pause and then state the point.'],['Lead with the point','Do not bury your answer under background.','“The outstanding item is X. I’m addressing it today.”'],['Replace weakeners','Reduce “just,” “maybe,” “I think,” “sorry to bother you.”','Use “I recommend,” “I’ll confirm,” “Could you please clarify?”'],['Thought units','Speak one idea at a time instead of one long sentence.','Point → reason → next step.'],['Recover smoothly','If you lose your words, stop and restart the sentence.','“Let me put that more clearly.”'],['Sound firm, not harsh','Directness and courtesy can exist together.','“Could you please confirm by Thursday?”']].map(x=>`<div class="card"><span class="tag">${x[0]}</span><h3>${x[1]}</h3><p class="mini">${x[2]}</p></div>`).join('')}</div><div class="section card"><h3>60-second confidence drill</h3><p class="mini">Stand or sit upright. Breathe once. Say: what is happening → what matters → what you recommend → what happens next. Record it in the Speaking Lab and compare your pace after a week.</p><button class="btn" onclick="go('speaking')">Record the drill</button></div>`}
function renderLibrary(){return `<div class="head"><div><h2>Guides, Blogs & Study Library</h2><p>Short lessons you can revisit when a skill needs work.</p></div></div><div class="grid g2">${blogs.map((b,i)=>`<article class="card article"><span class="tag">Guide ${i+1}</span><h3>${b[0]}</h3><p>${b[1]}</p><div class="callout">${b[2]}</div></article>`).join('')}</div><div class="section card"><h3>Advanced study principles</h3><ul><li>Use active recall: answer before looking at the model.</li><li>Use deliberate practice: repeat one weak skill instead of repeating everything.</li><li>Record yourself regularly so improvement is audible, not only visible.</li><li>Transfer vocabulary into multiple contexts rather than memorizing definitions.</li><li>Review previous days. Mature communication comes from noticing patterns over time.</li></ul></div>`}
function renderNotes(){return `<div class="head"><div><h2>Side Notes</h2><p>A permanent scratchpad for phrases, corrections, vocabulary and work communication ideas.</p></div></div><div class="card"><textarea id="fullNotes" class="answer" style="min-height:430px">${esc(state.notes)}</textarea><p class="mini">This is the same note space shown in the side rail. It auto-saves.</p></div>`}
function renderSettings(){return `<div class="head"><div><h2>Settings & Data</h2><p>Your practice data stays in this browser unless you export it.</p></div></div><div class="grid g2"><div class="card"><h3>120-day start date</h3><p class="mini">Current start: ${esc(state.startDate)}</p><input id="startDate" class="input" type="date" value="${esc(state.startDate)}"><button class="btn" id="saveStart" style="margin-top:8px">Save start date</button></div><div class="card"><h3>Backup</h3><p class="mini">Export your progress before changing devices or browsers.</p><div class="actions"><button class="btn" onclick="exportData()">Export JSON</button><button class="btn ghost" id="importBtn">Import JSON</button><input type="file" id="importFile" accept=".json" hidden></div></div><div class="card"><h3>Reset</h3><p class="mini">This removes progress from this browser. Audio recordings are separate browser data.</p><button class="btn" id="resetBtn">Reset progress</button></div></div>`}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SpeakUp-120-day-progress.json';a.click()}
function bind(){
 document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{go(b.dataset.view);document.getElementById('sidebar').classList.remove('open')});
 document.getElementById('fbSpeak')?.addEventListener('click',()=>{let t=document.getElementById('speakAnswer').value;document.getElementById('speakFeedback').innerHTML=feedback(t);state.answers[current().day] ||= {};state.answers[current().day].speaking=t;save()});
 document.getElementById('saveSpeak')?.addEventListener('click',()=>{let t=document.getElementById('speakAnswer').value,s=evaluate(t);state.answers[current().day] ||= {};state.answers[current().day].speaking=t;mark('speaking',s.overall)});
 document.getElementById('recBtn')?.addEventListener('click',beginRecord); if(document.getElementById('audioList'))loadAudio();
 [['Vocab','vocab'],['Work','work'],['Read','read'],['Write','write'],['Network','network']].forEach(([label,key])=>{
  let input=document.getElementById(key==='vocab'?'vocabAnswer':key==='work'?'workAnswer':key==='read'?'readingAnswer':key==='write'?'writeAnswer':'networkAnswer');
  let fb=document.getElementById('fb'+label),sv=document.getElementById('save'+label);
  if(input&&fb)fb.onclick=()=>{let f=feedback(input.value);document.getElementById(key==='vocab'?'vocabFeedback':key==='work'?'workFeedback':key==='read'?'readFeedback':key==='write'?'writeFeedback':'networkFeedback').innerHTML=f;state.answers[current().day] ||= {};state.answers[current().day][key==='vocab'?'vocabulary':key==='work'?'workplace':key==='read'?'reading':key==='write'?'writing':'networking']=input.value;save()};
  if(input&&sv)sv.onclick=()=>{let map={vocab:'vocabulary',work:'workplace',read:'reading',write:'writing',network:'networking'},f=feedback(input.value),s=evaluate(input.value);state.answers[current().day] ||= {};state.answers[current().day][map[key]]=input.value;mark(map[key],s.score||s.overall)};
 });
 let tb=document.getElementById('typingCheck');if(tb)tb.onclick=()=>{let source=document.getElementById('typingSource').textContent.trim(),typed=document.getElementById('typingInput').value.trim(),correct=0,n=Math.min(source.length,typed.length);for(let i=0;i<n;i++)if(source[i]===typed[i])correct++;let acc=source.length?Math.round(correct/source.length*100):0;state.typingBest=Math.max(state.typingBest,acc);save();document.getElementById('typingFeedback').innerHTML=`<div class="feedback"><h4>Typing feedback</h4><div class="fbgrid"><div class="pill"><b>${acc}%</b><small>Accuracy</small></div><div class="pill"><b>${typed.length}</b><small>Characters typed</small></div><div class="pill"><b>${Math.max(0,source.length-typed.length)}</b><small>Characters missing</small></div><div class="pill"><b>${state.typingBest}%</b><small>Best</small></div></div><p class="mini">${acc>=95?'Excellent accuracy. Now work on speed.':'Accuracy first. Slow down and reproduce the punctuation exactly.'}</p></div>`;if(acc>=80)mark('typing',acc)};
 document.getElementById('typingClear')?.addEventListener('click',()=>document.getElementById('typingInput').value='');
 document.getElementById('readAloud')?.addEventListener('click',()=>speechSynthesis.speak(new SpeechSynthesisUtterance(current().novel[2])));
 document.getElementById('stopRead')?.addEventListener('click',()=>speechSynthesis.cancel());
 document.getElementById('fullNotes')?.addEventListener('input',e=>{state.notes=e.target.value;save();document.getElementById('sideNotes').value=state.notes});
 document.getElementById('saveStart')?.addEventListener('click',()=>{state.startDate=document.getElementById('startDate').value||state.startDate;save();toast('Start date saved');render()});
 document.getElementById('resetBtn')?.addEventListener('click',()=>{if(confirm('Reset all SpeakUp progress?')){state={startDate:new Date().toISOString().slice(0,10),completed:{},history:{},answers:{},scores:{},notes:'',recordings:[],selectedDay:1,streak:0,lastCompleted:null,typingBest:0};save();render();toast('Progress reset')}});
 document.getElementById('importBtn')?.addEventListener('click',()=>document.getElementById('importFile').click());
 document.getElementById('importFile')?.addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast('Progress imported')}catch{toast('Invalid backup file')}};r.readAsText(f)});
}
function render(){let view=location.hash.slice(1)||'today';let fn={today:renderToday,journey:renderJourney,history:renderHistory,speaking:renderSpeaking,vocabulary:renderVocabulary,workplace:renderWorkplace,reading:renderReading,writing:renderWriting,typing:renderTyping,networking:renderNetworking,confidence:renderConfidence,library:renderLibrary,notes:renderNotes,settings:renderSettings}[view]||renderToday;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.getElementById('crumb').textContent=view==='today'?'Today':view.replace(/^\w/,m=>m.toUpperCase()).replace('-', ' ');document.getElementById('streakSide').textContent=state.streak;document.getElementById('dateNow').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});try{document.getElementById('app').innerHTML=fn();}catch(err){console.error(err);document.getElementById('app').innerHTML='<div class="card error"><h2>Something went wrong</h2><p>SpeakUp could not load this section. Your saved data is safe. Please refresh the page.</p><button class="btn" onclick="go(\'today\')">Return to Today</button></div>';}document.getElementById('sideNotes').value=state.notes||'';bind()}
document.getElementById('notesBtn').onclick=()=>document.getElementById('notesRail').classList.add('open');
document.getElementById('closeNotes').onclick=()=>document.getElementById('notesRail').classList.remove('open');
document.getElementById('sideNotes').addEventListener('input',e=>{state.notes=e.target.value;save()});
document.getElementById('hamb').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){e.preventDefault();go(nav.dataset.view);document.getElementById('sidebar')?.classList.remove('open');return;}const day=e.target.closest('[data-day]');if(day){e.preventDefault();selectDay(Number(day.dataset.day));}}); 
window.addEventListener('hashchange',render);state.selectedDay=state.selectedDay||dayNow();save();render();
