const pages=document.querySelectorAll('.page'),nav=document.querySelectorAll('.nav');
function go(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
nav.forEach(n=>n.onclick=()=>go(n.dataset.page));
function exampleSpeech(){document.getElementById('speech').value="The file is progressing well. I contacted the adjuster yesterday and I'm waiting for the medical records. I'll follow up by Friday if I don't hear back."}
function coachSpeech(){const x=document.getElementById('speech').value.trim(),f=document.getElementById('speechFeedback');if(!x){f.innerHTML="<b>Start with your own answer.</b> Focus on what you did, where things stand, and what's next.";f.classList.add('show');return}const score=x.length>100?88:x.length>60?82:74;f.innerHTML="<b>Coach feedback · "+score+"/100</b><br>"+(x.length<60?"Add one more detail about the current status or next step. ":"Good structure. ")+"Keep sentences short and end with a clear next action.";f.classList.add('show');const s=document.getElementById('sessions');if(s)s.textContent='19'}
function coachEmail(){const x=document.getElementById('email').value.trim(),f=document.getElementById('emailFeedback');if(!x){f.innerHTML="<b>Write a quick draft first.</b> It can be rough.";f.classList.add('show');return}f.innerHTML="<b>Coach feedback</b><br>Make the request specific, keep the tone polite, and make the next action clear.<br><br><b>Try:</b> “When you have a chance, could you please provide an update?”";f.classList.add('show')}
function openScenario(t,x){document.getElementById('modalTitle').textContent=t;document.getElementById('modalText').textContent=x;document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function speak(t){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}
document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()}